name: wasdu_mobile2
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.1.1
  get: ^4.6.5
  intl: ^0.17.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
